# This file was generated by GoReleaser. DO NOT EDIT.
cask "hookset" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "aa9b0246d38cf638844374720813b5b01399eb7a2df52b465f55323cc8ff834f"
      url "https://github.com/bulga138/hookset/releases/download/v#{version}/hookset_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c2c0639f2c0ef4326bad21c8fcdf0bf2d0ed7611a906216370b1358495d7ae17"
      url "https://github.com/bulga138/hookset/releases/download/v#{version}/hookset_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "55f5637facaf3e29b77302aa3d029b517761140aee3b4478973097cbb6f9f627"
      url "https://github.com/bulga138/hookset/releases/download/v#{version}/hookset_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c07d5ac1649ba7d2f18729a6802bc3edaf759598e34fe7a592c159284d7c9c8"
      url "https://github.com/bulga138/hookset/releases/download/v#{version}/hookset_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hookset"
  desc "Git 2.54 config-native hook manager — no Husky, no lint-staged"
  homepage "https://bulga138.github.io/hookset"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hookset"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hookset"]
    end
  end

  # No zap stanza required

end
